// Copyright (c) Microsoft Corporation
// License: MIT OR Apache-2.0

//! Direct FFI bindings to the WDDM display miniport APIs from the Windows
//! Driver Kit (WDK)
//!
//! This module contains all bindings to functions, constants, methods,
//! constructors and destructors in the following header: `dispmprt.h`. That
//! header transitively includes `video.h`, `d3dkmddi.h` and `d3dkmdt.h`; the
//! latter two live in the WDK's `shared` include directory, not `km`.
//!
//! Types are not included in this module, but are available in the top-level
//! `wdk_sys` module.
//!
//! Linking is provided by `displib.lib`, which exports `DxgkInitialize` and
//! `DxgkInitializeDisplayOnlyDriver` among 16 symbols total.

#[allow(
    missing_docs,
    reason = "most items in the WDK headers have no inline documentation, so bindgen is unable to \
              generate documentation for their bindings"
)]
mod bindings {
    #[allow(
        clippy::wildcard_imports,
        reason = "the underlying c code relies on all type definitions being in scope, which \
                  results in the bindgen generated code relying on the generated types being in \
                  scope as well"
    )]
    #[allow(
        unused_imports,
        reason = "in certain versions of the WDK, there are no functions related to display \
                  miniports that can be generated by bindgen, so these types are unused"
    )]
    use crate::types::*;

    include!(concat!(env!("OUT_DIR"), "/display.rs"));
}
#[allow(
    unused_imports,
    reason = "in certain versions of the WDK, there are no functions related to display miniports \
              that can be generated by bindgen, so the `bindings` module is empty"
)]
pub use bindings::*;
